Slight Rimac Buff
fkk-cz/noire_vehicles pull request #1022
Opened 2022-05-05 02:07 UTC by cxerq

2022-05-05 07:59 UTC, fkk-cz requested changes

2022-05-05 07:59 UTC, fkk-cz commented on DATA/rimac_data/handling.meta
> -			<fInitialDriveMaxFlatVel value="243.900000"/>
This old value implies a top speed of ~199.26 MPH. If the vehicle is 'only' doing 180 that indicates `fInitialDragCoeff` is the issue. Try lowering the value to around 5.0 to see if that helps.

2022-05-06 07:28 UTC, merged

2022-05-06 07:28 UTC, fkk-cz commented
Closes #1018.

2022-05-06 16:12 UTC, Stagonium commented
This brought the top speed I could reach to 181mph, up from 175mph.

2022-05-06 16:19 UTC, glefave0209 commented
I got the same result. It governs out at 182

2022-05-06 16:21 UTC, No-Yes1 commented
Make another vehicle issue.