Tweaks
fkk-cz/noire_vehicles pull request #795
Opened 2021-12-03 22:15 UTC by ZacLuxton

2021-12-08 22:12 UTC, fkk-cz requested changes

2021-12-08 22:12 UTC, fkk-cz commented on DATA/hayabusa_data/handling.meta
> +			<fTractionCurveMin value="3.000000"/>
> tweak(hayabusa) - nerf traction values slightly

Pretty sure fTractionCurveMin is supposed to be lower than fTractionCurveMax.

2021-12-08 22:12 UTC, fkk-cz commented on DATA/ZB1_data/handling.meta
> +			<fTractionCurveMin value="3.000000"/>
Same with this one.

2021-12-08 22:22 UTC, ZacLuxton commented on DATA/hayabusa_data/handling.meta
> +			<fTractionCurveMin value="3.000000"/>
Didn't you do 3.00000 for the super cars a while ago? to make them slide on the deserts etc etc? P. sure that was a thing in the past unless i'm tripping

2021-12-08 22:28 UTC, ZacLuxton commented on DATA/ZB1_data/handling.meta
> +			<fTractionCurveMin value="3.000000"/>
Didn't you do 3.00000 for the super cars a while ago? to make them slide on the deserts etc etc? P. sure that was a thing in the past unless i'm tripping

2021-12-09 05:22 UTC, fkk-cz commented on DATA/hayabusa_data/handling.meta
> +			<fTractionCurveMin value="3.000000"/>
No that was `fTractionLossMult` which might be a better fix for vehicles handling too good in the snow.

2021-12-09 07:13 UTC, ZacLuxton commented on DATA/hayabusa_data/handling.meta
> +			<fTractionCurveMin value="3.000000"/>
It looks like you just tweaked those two, so i'll revert it my side

2021-12-13 09:13 UTC, merged